### ISSUE TITLE
Protect API keys

### ISSUE THREAD

**Issue by daschachter** [AnshG714/sweeger#2]
Our project will use a variety of APIs (e.g. YouTube Data API). In order to protect critical information (i.e. not push private information to GitHub), we can use an encryption service, like [BlackBox](https://github.com/StackExchange/blackbox).

**Comment by AnshG714** [comment]
@daschachter Great thought! However, instead of encrypted API keys, we can also use [Python environment variables](https://help.pythonanywhere.com/pages/environment-variables-for-web-apps/) as this is usually done when building web applications. We can then set these environment variables on our hosting platform too.

**Comment by AnshG714** [comment]
.env files are gitignored

**Comment by daschachter** [comment]
@AnshG714 Interesting -- I'm not too familiar with web apps, but the Python environment variables makes sense. I used BlackBox on the last hackathon and essentially it allows us to share a .env file only amongst us four via GitHub (so we don't each need our own keys). I'm thinking that we can set this up for now (it is relatively simple/lightweight) until we have our code hosted somewhere, and then set up on the host via environment variables. In my mind, hosting the code will not be necessary for the MVP (but we can discuss at the meeting). What are your thoughts?

**Comment by AnshG714** [comment]
Okay, sounds like a good plan!
